name: "${PROJECT_NAME}_${ENVIRONMENT}"

networks:
  network_server:
    name: "net_${PROJECT_NAME}_${ENVIRONMENT}"

volumes:
  src:
  environments:

services:
  #APP LARAVEL
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: "${PROJECT_NAME}_${ENVIRONMENT}"
    container_name: "${PROJECT_NAME}_${ENVIRONMENT}"
    deploy:
      resources:
        limits:
          cpus: "${LIMIT_CPUS}"
          memory: "${LIMIT_MEMORY}"
    restart: "${RESTART}"
    volumes:
      - ./environments/.env:/var/www/html/.env
    networks:
      - network_server

  #WEB SERVER FOR APP LARAVEL NGINX
  server:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: "server_${PROJECT_NAME}_${ENVIRONMENT}"
    container_name: "server_${PROJECT_NAME}_${ENVIRONMENT}"
    deploy:
      resources:
        limits:
          cpus: "${SERVER_LIMIT_CPUS}"
          memory: "${SERVER_LIMIT_MEMORY}"
    restart: "${RESTART}"
    volumes:
      - ./environments/.env:/var/www/html/.env
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network_server
